version = 0.1
[default.deploy.parameters]
stack_name = "to-do-list-basic"
resolve_s3 = true
s3_prefix = "to-do-list-basic"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
